# Generated by Django 3.1.4 on 2021-01-01 15:52

from django.db import migrations


INITIAL_ENTRIES = [
    ("tve", "https://www.rtve.es/directo/la-1/", "https://rtve.es/contenidos/imagenes/directo_fb_la1.jpg"),
    ("Antena 3", "https://www.atresplayer.com/directos/antena3/", "https://imagenes.atresplayer.com/atp/clipping/cmsimages02/2020/01/14/A6A0AABD-8E66-467B-AB34-C2BA2B180ACD//720x540.jpg"),
]

def create_tv_entries(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TVEntry = apps.get_model("web", "TVEntry")
    for id_, url, image in INITIAL_ENTRIES:
        entry = TVEntry.objects.using(db_alias).create(
            title=id_,
            url=url,
            image_url=image,
        )
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tv_entries),
    ]
